### ISSUE TITLE
Currently the app is not working

### ISSUE THREAD

**Issue by Jon-Lam** [Elec0/SlugStop#1]
I am assuming this is because of the BUS server being done?

Also, I'm mainly submitting this because I could not find any other contact info. I was wondering how/where you received access to GET data and API. Is it open to the public for use?

**Comment by Elec0** [comment]
I totally didn't notice this.
Yeah, the app not working was only because of TAPS' server not working. 
Yes, the data is open for public use: http://bts.ucsc.edu:8081/location/get
